import Cover from "../cover.jpg";
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="w-full relative mb-20">
          <h1 className={styles.title}>
            Deb The <a href="https://localhost:3000/cREE">Builder</a>
          </h1>
            {/* <div className="fixed -z-50 left-0 right-0 p-20 h-56 mb-20 rounded-lg w-full">
              <Image src={Cover} alt={"Deb The Builder"} className="w-full" />
            </div> */}
        </div>
        
       
      </main>
    </div>
  )
}
